### ISSUE TITLE
Crash when using /spawnname and no entity selected

### ISSUE THREAD

**Issue by kddekadenz** [Hirato/lamiae#8]
We're not using the most up to date version for Kelgar, but this problem may still exist in this way.

If you have no entity selected and use the command /spawnname, the game crashes.
If you've fixed it by now, please ignore.

**Comment by Hirato** [comment]
I can't reproduce it.
By the looks of it that code hasn't changed since f7a64629 which was late 2013

**Comment by kddekadenz** [comment]
That's really about the time we last updated :x 
I downloaded the new version and now it's gone.

It's about time to update - but please, can you reset the edit camera to default again?
The new one feels unintuitive. It's also ways slower to go to each edge and confusing.
I also don't see the point of showing the edit menus all the time. That feels rather distracting.
The new look of the menus in editing is wonderful and super useful, though.

Some ideas:
- mapmodel preview is super laggy with a normal amount of game models (40-60) - maybe just a static image or switch back to text?
- add the binds for the blendbrushes again, as known from Sauerbraten - speeds things up quite a bit

Also, I think you would quite like to see the beautiful ruins we made with Lamiae:
http://kelgargame.weebly.com/blog

Sorry for putting this all into issues!
One last thing: We will release all the models, sounds and textures piece by piece as CC-BY.
Would be super useful to create an asset pool for the engine!
Right now I'm checking options to gather money for working 3 months full-time on Kelgar, to be able to devote the time it needs.

**Comment by Hirato** [comment]
You can press TAB to toggle the mouse mode.

As for asset pools, you'll notice that the model and texture files are split into two core files, bit like fontconfig does. Just make 90_kelgar.cfg files or something like that alongside. 

If the edit panels are that much of a bother, you can just turn them off.
